import 'package:app_dimonis/api/db_connection.dart';
import 'package:app_dimonis/models/firebase/firebase_gimcama.dart';
import 'package:app_dimonis/models/state/gimcama.dart';
import 'package:app_dimonis/providers/dimoni_provider.dart';
import 'package:firebase_database/firebase_database.dart';

class GimcanaProvider {
  List<Gimcama> _gimcanes = [];

  final DimoniProvider dimoniProvider;

  void Function() notifyListeners;

  GimcanaProvider(this._gimcanes, this.dimoniProvider, this.notifyListeners);

  static Future<List<FirebaseGimana>> getGimcames() async {
    final ref = SignleDBConn.getDatabase().ref('/gimcames');
    final snapshot = await ref.get();
    if (snapshot.exists) {
      var res = snapshot.value as Map;
      Map<Object, dynamic> json = res.cast<String, dynamic>();
      List<FirebaseGimana> gimcames = [];
      json.forEach((key, value) {
        Map<String, dynamic> b = value.cast<String, dynamic>();
        FirebaseGimana gimcama = FirebaseGimana.fromMap(b, id: key.toString());
        gimcames.add(gimcama);
      });
      return gimcames;
    } else {
      return [];
    }
  }

  static List<Gimcama> mapFirebaseGimcanaToGimcana(
      List<FirebaseGimana> gimcames, DimoniProvider dimoniProvider) {
    List<Gimcama> gimcanes = [];
    for (var gimcama in gimcames) {
      print('gimcama: ${gimcama.id}');
      List<Ubication> ubications = [];
      for (var dimoniz in gimcama.dimonis.entries) {
        var dimoniId = dimoniz.key;
        print('dimoniId: $dimoniId');
        var dimoniData = dimoniz.value;
        var dimoni = dimoniProvider.getDimoniById(dimoniId);
        var ubication = Ubication(
          dimoni: dimoni,
          x: dimoniData['x'],
          y: dimoniData['y'],
        );
        ubications.add(ubication);
      }
      var gimcana = Gimcama(
        nom: gimcama.nom,
        start: gimcama.start,
        end: gimcama.end,
        propietari: gimcama.propietari,
        id: gimcama.id,
        ubications: ubications,
      );
      gimcanes.add(gimcana);
    }
    return gimcanes;
  }

  /// ID is autogenerated
  void saveGimcama(FirebaseGimana gimcama) {
    var ref = getRef();
    final newGimcamaRef = ref.push();
    newGimcamaRef.set(gimcama.toMap());
    final ubications = gimcama.dimonis.entries
        .map((e) => Ubication(
              dimoni: dimoniProvider.getDimoniById(e.key),
              x: e.value['x'],
              y: e.value['y'],
            ))
        .toList();

    gimcanes.add(Gimcama(
      nom: gimcama.nom,
      start: gimcama.start,
      end: gimcama.end,
      propietari: gimcama.propietari,
      id: newGimcamaRef.key!,
      ubications: ubications,
    ));
    notifyListeners();
  }

  void removeGimcama(FirebaseGimana gimcama) {
    var ref = getRef();
    ref.child(gimcama.id).remove();
    gimcanes.removeWhere((element) => element.id == gimcama.id);
    notifyListeners();
  }

  void updateGimcama(FirebaseGimana gimcama) {
    var ref = getRef();
    ref.child(gimcama.id).set(gimcama.toMap());
    gimcanes.removeWhere((element) => element.id == gimcama.id);
    final ubications = gimcama.dimonis.entries
        .map((e) => Ubication(
              dimoni: dimoniProvider.getDimoniById(e.key),
              x: e.value['x'],
              y: e.value['y'],
            ))
        .toList();

    gimcanes.add(Gimcama(
      nom: gimcama.nom,
      start: gimcama.start,
      end: gimcama.end,
      propietari: gimcama.propietari,
      id: gimcama.id,
      ubications: ubications,
    ));
    notifyListeners();
  }

  void reload() async {
    final firebaseGimames = await GimcanaProvider.getGimcames();
    _gimcanes = mapFirebaseGimcanaToGimcana(firebaseGimames, dimoniProvider);

    notifyListeners();
  }

  Gimcama getGimcanaById(String id) =>
      _gimcanes.firstWhere((element) => element.id == id);

  DatabaseReference getRef() => SignleDBConn.getDatabase().ref('/gimcames');

  List<Gimcama> get gimcanes => _gimcanes;
}
